name = "DWaveNeal"
uuid = "870cdf72-5502-4b10-839c-127ceab78f22"
authors = ["Pedro Maciel Xavier <pedroxavier@psr-inc.com.br>"]
version = "0.5.0"

[deps]
DWave = "4d534982-bf11-4157-9e48-fe3a62208a50"

[compat]
DWave = "0.5.2"
julia = "1.10"
