name = "DWaveNeal"
uuid = "870cdf72-5502-4b10-839c-127ceab78f22"
authors = ["Pedro Maciel Xavier <pedromxavier@poli.ufrj.br>"]
version = "0.1.0"

[deps]
Anneal = "e4d9eb7f-b088-426e-aeb5-1c0dae3d8abb"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
