name = "DWaveNeal"
uuid = "870cdf72-5502-4b10-839c-127ceab78f22"
authors = ["Pedro Maciel Xavier <pedroxavier@psr-inc.com.br>"]
version = "0.4.0"

[deps]
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
QUBODrivers = "a3f166f7-2cd3-47b6-9e1e-6fbfe0449eb0"

[compat]
PythonCall = "0.9.12"
QUBODrivers = "0.2"
julia = "1.6"
